In [1]:
from google.colab import files
uploaded = files. upload()

Saving apple_products_pricing_2020_2026.csv to apple_products_pricing_2020_2026.csv

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('apple_products_pricing_2020_2026.csv')

In [4]:
df.head()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35

In [ ]:
df.shape

(80000, 14)

In [ ]:
df.describe()

,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Rating,Reviews_Count
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,963.959125,94467.994250,782.769855,74628.342439,21.418826,4.450099,2405.995925
std,470.086413,46068.468464,461.673970,45117.872172,16.697310,0.269782,1973.630852
min,329.000000,32242.000000,109.930000,9157.680000,-2.000000,3.800000,10.000000
25%,599.000000,58702.000000,432.930000,41686.835000,6.700000,4.300000,896.000000
50%,799.000000,78302.000000,699.740000,67324.020000,21.300000,4.400000,1893.500000
75%,1199.000000,117502.000000,989.112500,96568.117500,36.800000,4.700000,3383.000000
max,1999.000000,195902.000000,2038.970000,203668.710000,73.100000,4.900000,11526.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               80000 non-null  object
 1   Platform           80000 non-null  object
 2   Product_Category   80000 non-null  object
 3   Model_Name         80000 non-null  object
 4   Condition          80000 non-null  object
 5   Launch_Price_USD   80000 non-null  int64
 6   Launch_Price_INR   80000 non-null  int64
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct       80000 non-null  float64
 10  Sale_Event         6649 non-null   object
 11  Stock_Status       80000 non-null  object
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64
dtypes: float64(4), int64(3), object(7)
memory usage: 8.5+ MB

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.isnull().sum()

Date                     0
Platform                 0
Product_Category         0
Model_Name               0
Condition                0
Launch_Price_USD         0
Launch_Price_INR         0
Current_Price_USD        0
Current_Price_INR        0
Discount_Pct             0
Sale_Event           73351
Stock_Status             0
Rating                   0
Reviews_Count            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[['Platform','Product_Category','Condition','Sale_Event','Stock_Status']].nunique()

Platform            2
Product_Category    4
Condition           2
Sale_Event          4
Stock_Status        3
dtype: int64

In [ ]:
df['Platform'].value_counts()

Platform
Flipkart    40043
Amazon      39957
Name: count, dtype: int64

In [ ]:
df['Product_Category'].value_counts()

Product_Category
iPhone    28589
Mac       18020
Watch     17865
iPad      15526
Name: count, dtype: int64

In [ ]:
df['Condition'].value_counts()

Condition
New                    59985
Renewed/Refurbished    20015
Name: count, dtype: int64

In [ ]:
df['Sale_Event'].value_counts()

Sale_Event
Black Friday             2497
Big Billion Days         1579
Great Indian Festival    1504
Prime Day                1069
Name: count, dtype: int64

In [ ]:
df['Stock_Status'].value_counts()

Stock_Status
In Stock        55034
Out of Stock    13475
Low Stock       11491
Name: count, dtype: int64

In [ ]:
df.groupby('Product_Category')['Current_Price_USD'].mean()

Product_Category
Mac       1382.489812
Watch      398.638561
iPad       573.083382
iPhone     758.674718
Name: Current_Price_USD, dtype: float64

In [ ]:
df.groupby('Product_Category')['Current_Price_USD'].agg(['mean','max','min'])

                         mean      max     min
Product_Category
Mac               1382.489812  2038.97  332.76
Watch              398.638561   814.94  137.76
iPad               573.083382  1222.89  109.93
iPhone             758.674718  1222.98  226.61

In [ ]:
df.groupby(['Platform', 'Product_Category'])['Current_Price_USD'].agg(['mean','max','min'])

                                  mean      max     min
Platform Product_Category
Amazon   Mac               1386.412364  2038.97  332.76
         Watch              397.486116   814.93  143.62
         iPad               569.083277  1222.89  109.93
         iPhone             757.205425  1222.74  240.58
Flipkart Mac               1378.503180  2038.90  380.69
         Watch              399.767889   814.94  137.76
         iPad               577.109334  1222.81  111.14
         iPhone             760.133665  1222.98  226.61

In [ ]:
df.groupby(['Platform', 'Product_Category'])['Model_Name'].count()

Platform  Product_Category
Amazon    Mac                  9083
          Watch                8842
          iPad                 7788
          iPhone              14244
Flipkart  Mac                  8937
          Watch                9023
          iPad                 7738
          iPhone              14345
Name: Model_Name, dtype: int64

In [ ]:
df.groupby(['Platform', 'Product_Category']).size()

Platform  Product_Category
Amazon    Mac                  9083
          Watch                8842
          iPad                 7788
          iPhone              14244
Flipkart  Mac                  8937
          Watch                9023
          iPad                 7738
          iPhone              14345
dtype: int64

In [ ]:
df.groupby('Condition')['Rating'].mean()

Condition
New                    4.550404
Renewed/Refurbished    4.149483
Name: Rating, dtype: float64

In [ ]:
df.groupby('Condition')['Discount_Pct'].mean()

Condition
New                    16.708806
Renewed/Refurbished    35.534769
Name: Discount_Pct, dtype: float64

In [ ]:
df.groupby('Condition').agg({'Rating':'mean','Discount_Pct':'mean','Current_Price_USD': 'mean'})

                       Rating  Discount_Pct  Current_Price_USD
Condition
New                  4.550404     16.708806         830.066030
Renewed/Refurbished  4.149483     35.534769         641.023114

In [ ]:
df.groupby('Stock_Status')['Rating'].mean()

Stock_Status
In Stock        4.450696
Low Stock       4.447681
Out of Stock    4.449722
Name: Rating, dtype: float64

In [ ]:
df.groupby('Stock_Status')['Discount_Pct'].mean()

Stock_Status
In Stock        18.420487
Low Stock       27.281003
Out of Stock    28.665455
Name: Discount_Pct, dtype: float64

In [ ]:
df['Stock_Status'].value_counts()

Stock_Status
In Stock        55034
Out of Stock    13475
Low Stock       11491
Name: count, dtype: int64

In [ ]:
df.groupby('Stock_Status').agg({
    'Discount_Pct': 'mean',
    'Rating': 'mean',
    'Current_Price_USD': 'mean'
})

              Discount_Pct    Rating  Current_Price_USD
Stock_Status
In Stock         18.420487  4.450696         819.919547
Low Stock        27.281003  4.447681         708.515858
Out of Stock     28.665455  4.449722         694.365889

In [ ]:
df['Sale_Event'].value_counts(dropna=False)

Sale_Event
NaN                      73351
Black Friday              2497
Big Billion Days          1579
Great Indian Festival     1504
Prime Day                 1069
Name: count, dtype: int64

In [ ]:
df['Sale_Event'] = df['Sale_Event'].fillna('No Sale Event')

In [ ]:
df['Sale_Event'].value_counts()

Sale_Event
No Sale Event            73351
Black Friday              2497
Big Billion Days          1579
Great Indian Festival     1504
Prime Day                 1069
Name: count, dtype: int64

In [ ]:
df.groupby('Sale_Event')['Discount_Pct'].mean()

Sale_Event
Big Billion Days         37.023686
Black Friday             31.462155
Great Indian Festival    33.446077
No Sale Event            20.304699
Prime Day                34.435734
Name: Discount_Pct, dtype: float64

In [ ]:
df.groupby(['Platform', 'Sale_Event'])['Discount_Pct'].mean()

Platform  Sale_Event
Amazon    Black Friday             32.264889
          Great Indian Festival    33.446077
          No Sale Event            20.274995
          Prime Day                34.435734
Flipkart  Big Billion Days         37.023686
          Black Friday             30.696479
          No Sale Event            20.333588
Name: Discount_Pct, dtype: float64

In [ ]:
df.groupby('Product_Category')['Discount_Pct'].mean()

Product_Category
Mac       15.430627
Watch     26.266779
iPad      26.189856
iPhone    19.572790
Name: Discount_Pct, dtype: float64

In [ ]:
df.groupby(['Product_Category', 'Condition'])['Discount_Pct'].mean()

Product_Category  Condition
Mac               New                    10.394097
                  Renewed/Refurbished    30.477805
Watch             New                    21.723432
                  Renewed/Refurbished    39.546640
iPad              New                    21.742957
                  Renewed/Refurbished    39.423508
iPhone            New                    14.852983
                  Renewed/Refurbished    34.027995
Name: Discount_Pct, dtype: float64

In [ ]:
df.groupby('Product_Category')['Reviews_Count'].mean()

Product_Category
Mac       2284.959101
Watch     2380.098685
iPad      2808.002254
iPhone    2280.149883
Name: Reviews_Count, dtype: float64

In [ ]:
df['Date'].min(), df['Date'].max()

(Timestamp('2020-09-19 00:00:00'), Timestamp('2026-07-31 00:00:00'))

In [ ]:
df.to_csv('apple_ecommerce_cleaned.csv', index=False)